### ISSUE TITLE
失效了吗? 还能更新吗

### ISSUE THREAD

**Issue by doraemon1293** [hanFengSan/BilibiliCleaner#3]

**Comment by Morris-Wei** [comment]
同问，点击链接会出现
![image](https://user-images.githubusercontent.com/42715287/77488565-85e52180-6e70-11ea-9f73-21e60440432e.png)

**Comment by hanFengSan** [comment]
不维护了 也某些原因被google下架了

Morsen-wei <notifications@github.com> 于 2020年3月25日周三 08:14写道：
